version: 2.1

jobs:
  lint:
    docker:
      - image: cimg/node:14.15
    steps:
      - checkout
      - run: |
          node --version
          npm --version
      - run: npm install
      - run: npm run lint
  test:
    docker:
      - image: cimg/node:14.15
    steps:
      - checkout
      - run: |
          node --version
          npm --version
      - run: npm install
      - run: npm run test

workflows:
  lint-and-test:
    jobs:
      - lint
      - test
